# Generated by Django 5.1.2 on 2024-12-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0011_memberaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_boy',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_customer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_expert',
            field=models.BooleanField(default=False, verbose_name='Is Expert'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_seller',
            field=models.BooleanField(default=False, verbose_name='Is Seller'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_shop',
            field=models.BooleanField(default=False, verbose_name='Is Shop  '),
        ),
        migrations.AddField(
            model_name='user',
            name='is_user',
            field=models.BooleanField(default=False, verbose_name='Is User'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
