# Generated by Django 5.1.2 on 2024-12-05 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0013_user_age_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='SHOP',
            field=models.ForeignKey(default=46, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
