# Generated by Django 5.1.2 on 2024-12-05 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0014_products_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='PET',
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='PRODUCT',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pet_app.products'),
            preserve_default=False,
        ),
    ]
